### ISSUE TITLE
Experience SandPHP

### ISSUE THREAD

**Issue by havietduc91** [havietduc91/experience#4]
- Bug:

Fatal error: Uncaught exception 'Zend_Controller_Dispatcher_Exception' with message 'Cannot load controller class "IndexController" from file "/home/leeduc/code/gt/application/controllers/IndexController.php'' in /home/leeduc/code/sand-core/library/Zend/Controller/Dispatcher/Standard.php:347 Stack trace: #0 /home/leeduc/code/sand-core/library/Zend/Controller/Dispatcher/Standard.php(262): Zend_Controller_Dispatcher_Standard->loadClass('IndexController') #1 /home/leeduc/code/sand-core/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #2 /home/leeduc/code/sand-core/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch() #3 /home/leeduc/code/sand-core/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run() #4 /home/leeduc/code/gt/public/index.php(57): Zend_Application->run() #5 {main} thrown in /home/leeduc/code/sand-core/library/Zend/Controller/Dispatcher/Standard.php on line 347

Reason:
    + File phtml not found.
=> Fix: 
http://stackoverflow.com/questions/2130530/uncaught-exception-zend-controller-dispatcher-exception
- Create .phtml file has name same nameAction

**Comment by havietduc91** [comment]
DoBashJob:::
- Cách viết hàm:
  - $this->doBashJob($cond, $count = 0, $callback, $callbackExtraParams);
    - Hàm sẽ lấy ra các row thỏa mãn điều kiện $cond
    - Sau đó $row sẽ là tham biến của hàm $callback được thực hiện sau đó
    - Mỗi lần hàm $callback thực hiện $count $row
- Cách chạy:
  - Vào đường dần /queue/overview
    - Xóa tất cả các queued đang thực hiện khác đi, nếu không cần thiết
  - Vào đường dẫn /queue/start-daemon
    - Submit query phần Batch Processor

=> Lưu ý: 
- Mỗi lần ấn submit thì các lệnh sẽ được cache lại, nên khi thay đổi gì chúng ta cần vào /queue/overview để quit tiến trình cũ, và submit query lại
- Nếu muốn debug luôn trên code mà không cần thực hiện câu lệnh l()
  - Sau khi nhấn submit query lấy code phần success
  - Cộng thêm với dòng lệnh --debugCli=1 là có thể echo các đoạn code cần test

Enjoy!!!

**Comment by havietduc91** [comment]
What is ACID on database?

http://stackoverflow.com/questions/3740280/acid-and-database-transactions

ACID is a set of properties that you would like to apply when modifying a database.

```
Atomicity
Consistency
Isolation
Durability
```

 A transaction is a set of related changes which is used to achieve some of the ACID properties. Transactions are tools to achieve the ACID properties.
- Atomicity means that you can guarantee that all of a transaction happens, or none of it does; you can do complex operations as one single unit, all or nothing, and a crash, power failure, error, or anything else won't allow you to be in a state in which only some of the related changes have happened.
- Consistency means that you guarantee that your data will be consistent; none of the constraints you have on related data will ever be violated.
- Isolation means that one transaction cannot read data from another transaction that is not yet completed. If two transactions are executing concurrently, each one will see the world as if they were executing sequentially, and if one needs to read data that is written by another, it will have to wait until the other is finished.
- Durability means that once a transaction is complete, it is guaranteed that all of the changes have been recorded to a durable medium (such as a hard disk), and the fact that the transaction has been completed is likewise recorded.

So, transactions are a mechanism for guaranteeing these properties; they are a way of grouping related actions together such that as a whole, a group of operations can be atomic, produce consistent results, be isolated from other operations, and be durably recorded.

**Comment by havietduc91** [comment]
Các bước cần làm khi chuyển server:
- Backup cơ sở dữ liệu MongoDB
- Import redis
  - Khi chưa import lại redis có thể sẽ bị lỗi, hiển thị cơ sở dữ liệu sai, do dữ liệu được lấy từ redis, mà phần này lại chưa được import nên nó sẽ lấy dữ liệu từ redis cũ
  - Nếu xóa redis cũ mà chưa update redis mới vào sẽ báo lỗi invalid object id

=> refresh redis

**Comment by havietduc91** [comment]
Khi không muốn dùng file view của Action đó mà muốn dùng file view của 1 action khác:
- $this->setNoRenderer();
- echo $this->view->render('index/template_you_want_to_show.phtml');

**Comment by havietduc91** [comment]
how to backup and restore mongodb

Backup::

Restore::
- tar -xvf dump.20112013.tar.gz
- cd 20112013
- mongorestore

**Comment by havietduc91** [comment]
Tranning SMS: 26/7
- Gioi thieu lai ve JS callbacks & CL.utils
  - Callbacks
    - Chú ý đến widget/php-to-js.phtml
    - Xem set co ham filterNewObjectAjax khi tra ve du lieu
  - Utils (sand-utils)
    - Chua tat ca cac ham dung cho toan trang
      - Vi du: getCookie, setCookie, removeItem, conlose.log() => CL.utils.log
      - Xem lai localStorage setItem, getItem
- CMS news.local
  - Category
  - List
  - Image File Brower
- Code
  - Xem lai preDisPath o Plugin.php xu ly truoc tat ca cac action
  - Xem may ham dung chung cua Zend :: dispathLoopShutdown, preDispath......

**Comment by havietduc91** [comment]
Tai sao bo Dao_Node_Quora xuong 1 dong thi ko sao?
    Do quá trình đọc file ...... xem lại

**Comment by havietduc91** [comment]
- Khi tạo 1 host.local mới thì nên đổi cả tên demo.phtml => host.phtml ở trong layout QUAN TRỌNG

**Comment by havietduc91** [comment]
- Replace all in ubutun
  - cd $core/misc
  - less  replace.sh 
  -  find $dir -name "*.$ext" -print0 | xargs -0 sed --regexp-extended --in-place "s/$str_find/$str_repl/g

**Comment by havietduc91** [comment]
# TIÊU CHÍ CODE
- Controller 
  - Thin controller fat modal
    - Các hàm trong moda cũng ngắn ko được dài, nên tách nhỏ ra
    - (dài 1 gang tay, rộng chỉ khoảng 80 ký tự ......) (cập nhật dữ liệu)
- View
  - View là để hiển thị dữ liệu, không phải xử lý dữ liệu
  - Tách code php ra khỏi file view
  - => Thay đổi theme, và html sẽ tránh việc bị trùng php trong nhiều file view
  - Tách view sao cho đơn giản nhất
- CSS
  - Hạn chế đưa thêm thuộc tính, đưa thêm class vào
  - Kế thừa được các class trước thì càng tốt
  - => cái tiến performent
  - http://www.helloerik.com/the-subtle-magic-behind-why-the-bootstrap-3-grid-works
    - Đọc và xem lại phần padding
  - Tìm hiểu lập trình CSS, (less)
- Javascript
  - File js giới hạn trang sử dụng (lesson view)
  - Nên wrapper các event class trong 1 id để tránh trình duyệt phải loop toàn bộ các class đó trong toàn DOM TREE, mà chỉ cần loop trong id 
  - Trình duyệt sẽ cache lại ID, nên nếu dùng selecter bởi ID thì trình duyệt sẽ tìm nhanh hơn (giống như đánh index trong MYSQL)
  - Khác nhau giữa $("#id .class").on('click', fucntion) và $("#id").on('click', '.class', function()), cái thứ 2 nhanh hơn
  - Vì cái thứ nhất sẽ có nhiều handle, cái thứ 2 ID đại diện 1 handle, khi click sẽ mò vào cái con của nó
  - Search key word: event bubbling and propagation
  - http://www.quirksmode.org/js/events_order.html
  - http://gregfranko.com/jquery-best-practices
  - http://blog.codinghorror.com/the-principle-of-least-power/

**Comment by havietduc91** [comment]
- Tìm hiểu kỹ sự khác nhau giữa private & protected, public
- Tìm hiểu thêm về static
- Tìm hiểu sự khác nhau giữa các cách gọi $this-> và self::

http://board.phpbuilder.com/showthread.php?10354489-RESOLVED-php-class-quot-this-quot-or-quot-self-quot-keyword

```
Use $this to refer to the current object. Use self to refer to the current class.
 In other words, use  $this->member for non-static members, 
use self::$member for static members
```

**Comment by havietduc91** [comment]
Chưa hiểu tại sao vào answer.edx.local/quora/comment 
-------------------
- Luồng lại vào Dao trước mà lại ko vào action trước ?????

**Comment by havietduc91** [comment]
##### Not found edx.html

Do chưa tạo symlink, nên tạo symlink ở trong thư mục edx
- cd $edx
- ln -s /home/.../vieted-front assets
- ln -s /home/.../sand-core/assets sand-assets
